name: NPM Package Publishing Workflow

# Trigger the workflow when a pull request is closed in the 'main' branch
on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'

jobs:
  publish-npm:
    # Only run the job if the pull request is merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      # Checkout the project repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      # Publish the package to the npm registry
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_ACCESS_TOKEN }}
