name: Publish Package to npmjs
on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
jobs:
  publish-npm:
    # needs: version-bump
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      # Checkout project repository
      - uses: actions/checkout@v3
      # Setup Node.js environment
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      # Publish version to public repository
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_ACCESS_TOKEN }}
