name: Publish Package to npmjs
on:
  push:
    branches:
      - main 
jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm run version:bump

      - run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add package.json
          git commit -m "Bumped version"
          git push origin main

  publish-npm:
    needs: version-bump
    runs-on: ubuntu-latest
    steps:
      # Checkout project repository
      - uses: actions/checkout@v3
      # Setup Node.js environment
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      # Publish version to public repository
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_ACCESS_TOKEN }}
